source 'https://rubygems.org'

gem 'unicorn'
gem 'capistrano'
gem 'rvm-capistrano'
gem 'sinatra'
gem 'docsplit', git: 'git@github.com:chintanparikh/docsplit.git'
gem 'debugger'
gem 'json'
gem 'rest-client'
gem 'sinatra-logger'